### ISSUE TITLE
大神可以写一个食用方案吗～

### ISSUE THREAD

**Issue by qiaohaoforever** [WJerry0227/MusicComment163#1]

**Comment by Jiawei0227** [comment]
http://wjerry.top/2017/06/15/爬取网易云音乐评论/
http://wjerry.top/2017/06/17/Crawl-Netease-Music/

这两个你先看一下
整体思路其实还是蛮简单的，就是无脑爬
过程中用多线程加一下速度
然后注意要启动一个代理池通过代理去爬，不然爬的速度太快会被网易云把ip封掉

代理池的github：
https://github.com/WJerry0227/proxy_pool

**Comment by Jiawei0227** [comment]
我这个代码里面还加了多线程之类的 但是博客里面没来得及写 你先自己看看 有什么问题可以一起讨论

**Comment by Jiawei0227** [comment]
最近太忙了，以后有时间会重构一下整个代码
